<?php

namespace App\Module\Notification;

class NotificationServiceProvider extends \Illuminate\Support\ServiceProvider
{
    /**
     * @return void
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
